package com.datastream.mvp.dag;

import com.datastream.mvp.model.ControlRegistry;
import com.datastream.mvp.repository.ControlRegistryRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.*;

@Slf4j
@Component
public class LocalDagExecutor implements DagExecutor {

    private final ControlRegistryRepository controlRepo;
    private final ObjectMapper objectMapper;

    public LocalDagExecutor(ControlRegistryRepository controlRepo, ObjectMapper objectMapper) {
        this.controlRepo = controlRepo;
        this.objectMapper = objectMapper;
    }

    @Override
    public String execute(DagDefinition dag) throws Exception {
        log.info("[LocalDagExecutor] Translating DAG: {}", dag.getJobName());

        // Validate all nodes exist and are enabled
        for (DagDefinition.DagNode node : dag.getNodes()) {
            ControlRegistry control = controlRepo.findByType(node.getType())
                    .orElseThrow(() -> new RuntimeException("Unknown control type: " + node.getType()));
            if (!Boolean.TRUE.equals(control.getEnabled())) {
                throw new RuntimeException("Control disabled: " + node.getType());
            }
        }

        List<DagDefinition.DagNode> sorted = topologicalSort(dag);

        StringBuilder sql = new StringBuilder();
        sql.append("-- Generated by LocalDagExecutor\n");
        sql.append("-- Job: ").append(dag.getJobName()).append("\n");
        sql.append("SET 'execution.runtime-mode' = 'batch';\n");
        sql.append("SET 'parallelism.default' = '").append(dag.getParallelism()).append("';\n\n");

        Map<String, String> tableNames = new HashMap<>();
        Map<String, String> nodeSchemas = new HashMap<>();

        for (DagDefinition.DagNode node : sorted) {
            ControlRegistry control = controlRepo.findByType(node.getType()).get();
            String tableName = sanitizeTableName(node.getId());
            tableNames.put(node.getId(), tableName);

            boolean isSource = "input".equals(control.getCategory());
            boolean isSink = "output".equals(control.getCategory());

            if (isSource || isSink) {
                sql.append("-- Node: ").append(node.getLabel()).append(" (").append(node.getId()).append(")\n");
                if ("datagen_input".equals(node.getType())) {
                    sql.append(generateDatagenDDL(tableName, node.getParams()));
                    nodeSchemas.put(node.getId(), extractFieldsFromDatagenConfig(node.getParams()));
                } else if (isSink) {
                    String sourceFields = findIncomingSourceSchema(node.getId(), dag.getEdges(), nodeSchemas);
                    if (sourceFields != null) {
                        log.info("Schema propagation: replacing 'data STRING' with custom fields from source for node {}", node.getId());
                        String modifiedTemplate = replaceDataStringInDDL(control.getFlinkTemplate(), sourceFields);
                        sql.append(renderFlinkTemplate(modifiedTemplate, node.getParams(), tableName));
                    } else {
                        sql.append(renderFlinkTemplate(control.getFlinkTemplate(), node.getParams(), tableName));
                    }
                } else if (isSource) {
                    // Non-datagen input: render the DDL template directly and store schema
                    sql.append(renderFlinkTemplate(control.getFlinkTemplate(), node.getParams(), tableName));
                    String schema = extractFieldsFromDdlTemplate(control.getFlinkTemplate());
                    if (schema != null) {
                        nodeSchemas.put(node.getId(), schema);
                    }
                }
                sql.append("\n\n");
            }
        }

        for (DagDefinition.DagEdge edge : dag.getEdges()) {
            String sourceTable = tableNames.get(edge.getSource());
            String targetTable = tableNames.get(edge.getTarget());

            DagDefinition.DagNode transformNode = dag.getNodes().stream()
                    .filter(n -> n.getId().equals(edge.getTarget()))
                    .findFirst().orElse(null);

            if (transformNode != null) {
                ControlRegistry control = controlRepo.findByType(transformNode.getType()).get();
                if ("transform".equals(control.getCategory())) {
                    sql.append("INSERT INTO ").append(targetTable).append("\n")
                       .append(renderFlinkTemplate(control.getFlinkTemplate(),
                                transformNode.getParams(), transformNode.getId()))
                       .append("\n;\n\n");
                    continue;
                }
            }

            sql.append("INSERT INTO ").append(targetTable).append("\n")
               .append("SELECT * FROM ").append(sourceTable).append(";\n\n");
        }

        String flinkSql = sql.toString();
        log.info("Generated Flink SQL:\n{}", flinkSql);
        return flinkSql;
    }

    private String extractFieldsFromDatagenConfig(Map<String, Object> params) {
        if (params == null) return null;
        String fieldsConfig = params.getOrDefault("fieldsConfig", "[]").toString();
        if (fieldsConfig == null || fieldsConfig.isBlank() || "[]".equals(fieldsConfig)) return null;
        try {
            JsonNode fieldsArray = objectMapper.readTree(fieldsConfig);
            if (fieldsArray.isArray() && fieldsArray.size() > 0) {
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < fieldsArray.size(); i++) {
                    JsonNode field = fieldsArray.get(i);
                    String fieldName = field.has("name") ? field.get("name").asText() : "field" + i;
                    String fieldType = field.has("type") ? field.get("type").asText() : "STRING";
                    sb.append("  ").append(fieldName).append(" ").append(fieldType);
                    if (i < fieldsArray.size() - 1) sb.append(",\n");
                }
                return sb.toString();
            }
        } catch (Exception e) {
            log.warn("Failed to parse fieldsConfig: {}", e.getMessage());
        }
        return null;
    }

    /**
     * Extract column definitions from a CREATE TABLE DDL template.
     */
    private String extractFieldsFromDdlTemplate(String template) {
        try {
            int parenStart = template.indexOf('(');
            int parenEnd = template.indexOf(')');
            if (parenStart > 0 && parenEnd > parenStart) {
                String cols = template.substring(parenStart + 1, parenEnd).trim();
                if (!cols.isEmpty()) {
                    return cols;
                }
            }
        } catch (Exception e) {
            log.warn("Failed to extract fields from DDL template: {}", e.getMessage());
        }
        return null;
    }

    /**
     * Replace the 'data STRING' column definition in a DDL template with custom field definitions.
     */
    private String replaceDataStringInDDL(String template, String newFields) {
        return template.replaceAll("(?m)^\\s*data\\s+STRING\\s*$", newFields);
    }

    private String findIncomingSourceSchema(String nodeId, List<DagDefinition.DagEdge> edges, Map<String, String> nodeSchemas) {
        for (DagDefinition.DagEdge edge : edges) {
            if (edge.getTarget().equals(nodeId) && nodeSchemas.containsKey(edge.getSource())) {
                return nodeSchemas.get(edge.getSource());
            }
        }
        return null;
    }

    private String renderFlinkTemplate(String template, Map<String, Object> params, String nodeId) {
        String result = template;
        result = result.replace("${id}", sanitizeTableName(nodeId));
        if (params != null) {
            for (Map.Entry<String, Object> entry : params.entrySet()) {
                String placeholder = "${" + entry.getKey() + "}";
                String value = entry.getValue() != null ? entry.getValue().toString() : "";
                result = result.replace(placeholder, value);
            }
        }
        return result;
    }

    private String sanitizeTableName(String id) {
        return id.replaceAll("[^a-zA-Z0-9_]", "_");
    }

    private List<DagDefinition.DagNode> topologicalSort(DagDefinition dag) {
        Map<String, Integer> inDegree = new HashMap<>();
        Map<String, List<String>> adjacency = new HashMap<>();
        Map<String, DagDefinition.DagNode> nodeMap = new HashMap<>();

        for (DagDefinition.DagNode node : dag.getNodes()) {
            inDegree.put(node.getId(), 0);
            adjacency.put(node.getId(), new ArrayList<>());
            nodeMap.put(node.getId(), node);
        }
        for (DagDefinition.DagEdge edge : dag.getEdges()) {
            adjacency.get(edge.getSource()).add(edge.getTarget());
            inDegree.merge(edge.getTarget(), 1, Integer::sum);
        }

        Queue<String> queue = new LinkedList<>();
        for (Map.Entry<String, Integer> entry : inDegree.entrySet()) {
            if (entry.getValue() == 0) queue.add(entry.getKey());
        }

        List<DagDefinition.DagNode> result = new ArrayList<>();
        while (!queue.isEmpty()) {
            String nodeId = queue.poll();
            result.add(nodeMap.get(nodeId));
            for (String neighbor : adjacency.get(nodeId)) {
                inDegree.merge(neighbor, -1, Integer::sum);
                if (inDegree.get(neighbor) == 0) queue.add(neighbor);
            }
        }

        if (result.size() != dag.getNodes().size()) {
            throw new RuntimeException("DAG contains a cycle");
        }
        return result;
    }

    /**
     * Generate Flink SQL DDL for datagen connector based on fieldsConfig JSON
     */
    private String generateDatagenDDL(String tableName, Map<String, Object> params) {
        String rowsPerSecond = params != null && params.get("rowsPerSecond") != null 
                ? params.get("rowsPerSecond").toString() : "10";
        String fieldsConfig = params != null && params.get("fieldsConfig") != null 
                ? params.get("fieldsConfig").toString() : "[]";
        
        StringBuilder ddl = new StringBuilder();
        ddl.append("CREATE TABLE ").append(tableName).append(" (\n");
        
        // Try to parse fields from JSON config
        try {
            JsonNode fieldsArray = objectMapper.readTree(fieldsConfig);
            if (fieldsArray.isArray() && fieldsArray.size() > 0) {
                for (int i = 0; i < fieldsArray.size(); i++) {
                    JsonNode field = fieldsArray.get(i);
                    String fieldName = field.has("name") ? field.get("name").asText() : "field" + i;
                    String fieldType = field.has("type") ? field.get("type").asText() : "STRING";
                    ddl.append("  ").append(fieldName).append(" ").append(fieldType);
                    if (i < fieldsArray.size() - 1) ddl.append(",");
                    ddl.append("\n");
                }
            } else {
                ddl.append("  data STRING\n");
            }
        } catch (Exception e) {
            log.warn("Failed to parse fieldsConfig, using default: {}", e.getMessage());
            ddl.append("  data STRING\n");
        }
        
        ddl.append(") WITH (\n");
        ddl.append("  'connector' = 'datagen',\n");
        ddl.append("  'rows-per-second' = '").append(rowsPerSecond).append("'");
        
        // Add field-specific generation options
        try {
            JsonNode fieldsArray = objectMapper.readTree(fieldsConfig);
            if (fieldsArray.isArray()) {
                for (int i = 0; i < fieldsArray.size(); i++) {
                    JsonNode field = fieldsArray.get(i);
                    String fieldName = field.has("name") ? field.get("name").asText() : "field" + i;
                    
                    if (field.has("kind") && "sequence".equals(field.get("kind").asText())) {
                        ddl.append(",\n");
                        ddl.append("  'fields.").append(fieldName).append(".kind' = 'sequence'");
                        if (field.has("start")) {
                            ddl.append(",\n");
                            ddl.append("  'fields.").append(fieldName).append(".start' = '").append(field.get("start").asText()).append("'");
                        }
                        if (field.has("end")) {
                            ddl.append(",\n");
                            ddl.append("  'fields.").append(fieldName).append(".end' = '").append(field.get("end").asText()).append("'");
                        }
                    } else {
                        if (field.has("min")) {
                            ddl.append(",\n");
                            ddl.append("  'fields.").append(fieldName).append(".min' = '").append(field.get("min").asText()).append("'");
                        }
                        if (field.has("max")) {
                            ddl.append(",\n");
                            ddl.append("  'fields.").append(fieldName).append(".max' = '").append(field.get("max").asText()).append("'");
                        }
                        if (field.has("length")) {
                            ddl.append(",\n");
                            ddl.append("  'fields.").append(fieldName).append(".length' = '").append(field.get("length").asText()).append("'");
                        }
                    }
                }
            }
        } catch (Exception e) {
            log.warn("Failed to generate field options: {}", e.getMessage());
        }
        
        ddl.append("\n);\n");
        return ddl.toString();
    }
}